"""Initial1

Revision ID: 2abe27415388
Revises: 
Create Date: 2023-12-13 14:56:11.213391

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '2abe27415388'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
