"""Initial2

Revision ID: c43f2bbc2892
Revises: 2abe27415388
Create Date: 2023-12-13 18:41:13.635311

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c43f2bbc2892'
down_revision: Union[str, None] = '2abe27415388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
