"""Initial8

Revision ID: d6f958dcad89
Revises: 82a26bbb613a
Create Date: 2023-12-23 12:42:15.366561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6f958dcad89'
down_revision: Union[str, None] = '82a26bbb613a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
